### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by vendethiel** [barciszewski/TMX-S-Parser#1]
Hi.

I'm interested in your project, and I'd like to know if it works / is usable in Scala projects.

Thanks!

**Comment by barciszewski** [comment]
Hi Ven,

I would describe this project as 'inactive'.  I was using it as a way to learn some Scala and have a little fun.  At the time I posted the code, it did work, but there have been new releases of Scala and I would expect that there are some breaking changes.  I also would not necessarily describe this as idiomatic Scala.  Like I said, I was using the project to learn some Scala, and since Java is what I use daily, the code looks a lot more like Java than Scala.

**Comment by vendethiel** [comment]
Okay, thanks for your answer :-)
